<a href="https://colab.research.google.com/github/EngrAnsar/ML-Projects/blob/main/Project7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project Title:
# Data Preprocessing, Cleaning, visualization of
## Dataset name: "Digits Dataset "

**Importing Libraries**

**We need three Libraries for data manipulation.cleaning, visualization.**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**importing Dataset**

**downloaded kaggle**

In [ ]:
from google.colab import drive
import pandas as pd
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/My Drive/digits.csv")

Mounted at /content/drive

## **A- Data inpections**

**1-checking ist five rows**

In [ ]:
df.head()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
0,0,0,0,12,13,5,0,0,0,0,...,0,0,0,0,11,16,10,0,0,1
1,0,0,0,4,15,12,0,0,0,0,...,0,0,0,0,3,11,16,9,0,2
2,0,0,7,15,13,1,0,0,0,8,...,0,0,0,7,13,13,9,0,0,3
3,0,0,0,1,11,0,0,0,0,0,...,0,0,0,0,2,16,4,0,0,4
4,0,0,12,10,0,0,0,0,0,0,...,0,0,0,9,16,16,10,0,0,5

**2-checking last five rows**

In [ ]:
df.tail()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
1791,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,9
1792,0,0,6,16,13,11,1,0,0,0,...,0,0,0,6,16,14,6,0,0,0
1793,0,0,1,11,15,1,0,0,0,0,...,0,0,0,2,9,13,6,0,0,8
1794,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,9
1795,0,0,10,14,8,1,0,0,0,2,...,0,0,1,8,12,14,12,1,0,8

**3-checking details**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1796 entries, 0 to 1795
Data columns (total 65 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1796 non-null   int64
 1   0.1     1796 non-null   int64
 2   5       1796 non-null   int64
 3   13      1796 non-null   int64
 4   9       1796 non-null   int64
 5   1       1796 non-null   int64
 6   0.2     1796 non-null   int64
 7   0.3     1796 non-null   int64
 8   0.4     1796 non-null   int64
 9   0.5     1796 non-null   int64
 10  13.1    1796 non-null   int64
 11  15      1796 non-null   int64
 12  10      1796 non-null   int64
 13  15.1    1796 non-null   int64
 14  5.1     1796 non-null   int64
 15  0.6     1796 non-null   int64
 16  0.7     1796 non-null   int64
 17  3       1796 non-null   int64
 18  15.2    1796 non-null   int64
 19  2       1796 non-null   int64
 20  0.8     1796 non-null   int64
 21  11      1796 non-null   int64
 22  8       1796 non-null   int64
 23  0.9     1796 non-null   int64
 24  0.10    1796 non-null   int64
 25  4       1796 non-null   int64
 26  12      1796 non-null   int64
 27  0.11    1796 non-null   int64
 28  0.12    1796 non-null   int64
 29  8.1     1796 non-null   int64
 30  8.2     1796 non-null   int64
 31  0.13    1796 non-null   int64
 32  0.14    1796 non-null   int64
 33  5.2     1796 non-null   int64
 34  8.3     1796 non-null   int64
 35  0.15    1796 non-null   int64
 36  0.16    1796 non-null   int64
 37  9.1     1796 non-null   int64
 38  8.4     1796 non-null   int64
 39  0.17    1796 non-null   int64
 40  0.18    1796 non-null   int64
 41  4.1     1796 non-null   int64
 42  11.1    1796 non-null   int64
 43  0.19    1796 non-null   int64
 44  1.1     1796 non-null   int64
 45  12.1    1796 non-null   int64
 46  7       1796 non-null   int64
 47  0.20    1796 non-null   int64
 48  0.21    1796 non-null   int64
 49  2.1     1796 non-null   int64
 50  14      1796 non-null   int64
 51  5.3     1796 non-null   int64
 52  10.1    1796 non-null   int64
 53  12.2    1796 non-null   int64
 54  0.22    1796 non-null   int64
 55  0.23    1796 non-null   int64
 56  0.24    1796 non-null   int64
 57  0.25    1796 non-null   int64
 58  6       1796 non-null   int64
 59  13.2    1796 non-null   int64
 60  10.2    1796 non-null   int64
 61  0.26    1796 non-null   int64
 62  0.27    1796 non-null   int64
 63  0.28    1796 non-null   int64
 64  0.29    1796 non-null   int64
dtypes: int64(65)
memory usage: 912.2 KB

**4.Checking Rows and Coloumns:**

In [ ]:
df.shape

(1796, 65)

**5.Column Names**

In [ ]:
df.columns

Index(['0', '0.1', '5', '13', '9', '1', '0.2', '0.3', '0.4', '0.5', '13.1',
       '15', '10', '15.1', '5.1', '0.6', '0.7', '3', '15.2', '2', '0.8', '11',
       '8', '0.9', '0.10', '4', '12', '0.11', '0.12', '8.1', '8.2', '0.13',
       '0.14', '5.2', '8.3', '0.15', '0.16', '9.1', '8.4', '0.17', '0.18',
       '4.1', '11.1', '0.19', '1.1', '12.1', '7', '0.20', '0.21', '2.1', '14',
       '5.3', '10.1', '12.2', '0.22', '0.23', '0.24', '0.25', '6', '13.2',
       '10.2', '0.26', '0.27', '0.28', '0.29'],
      dtype='object')

**6.Data Types for Preprocessing**

In [ ]:
df.dtypes

0       int64
0.1     int64
5       int64
13      int64
9       int64
        ...
10.2    int64
0.26    int64
0.27    int64
0.28    int64
0.29    int64
Length: 65, dtype: object

**7.Label-based Data Selection (row and column)**

In [ ]:
df.loc[2]

0        0
0.1      0
5        7
13      15
9       13
        ..
10.2    13
0.26     9
0.27     0
0.28     0
0.29     3
Name: 2, Length: 65, dtype: int64

**8.Index-based Data Selection (row and column)**

In [ ]:
df.iloc[:,[3,4,5]]

      13   9   1
0     12  13   5
1      4  15  12
2     15  13   1
3      1  11   0
4     10   0   0
...   ..  ..  ..
1791  10  13   6
1792  16  13  11
1793  11  15   1
1794  10   7   0
1795  14   8   1

[1796 rows x 3 columns]

**Applying mathematical fuctions**

In [ ]:
df.describe()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
count,1796.0,1796.000000,1796.000000,1796.000000,1796.000000,1796.000000,1796.000000,1796.000000,1796.000000,1796.000000,...,1796.000000,1796.000000,1796.000000,1796.00000,1796.00000,1796.000000,1796.000000,1796.000000,1796.000000,1796.000000
mean,0.0,0.304009,5.204900,11.835189,11.849666,5.784521,1.363029,0.129733,0.005568,1.994989,...,0.206570,0.000557,0.279510,5.55735,12.08853,11.810134,6.767817,2.069042,0.364699,4.493318
std,0.0,0.907416,4.756148,4.249936,4.288055,5.666871,3.326546,1.037667,0.094248,3.196704,...,0.984663,0.023596,0.934539,5.10443,4.37586,4.935137,5.900105,4.091396,1.860620,2.864140
min,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.0,0.000000,1.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.00000,11.00000,10.000000,0.000000,0.000000,0.000000,2.000000
50%,0.0,0.000000,4.000000,13.000000,13.000000,4.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,4.00000,13.00000,14.000000,6.000000,0.000000,0.000000,4.000000
75%,0.0,0.000000,9.000000,15.000000,15.000000,11.000000,0.000000,0.000000,0.000000,3.000000,...,0.000000,0.000000,0.000000,10.00000,16.00000,16.000000,12.000000,2.000000,0.000000,7.000000
max,0.0,8.000000,16.000000,16.000000,16.000000,16.000000,16.000000,15.000000,2.000000,16.000000,...,13.000000,1.000000,9.000000,16.00000,16.00000,16.000000,16.000000,16.000000,16.000000,9.000000

# B-Data Cleaning

**1-checking Missing Values**

In [ ]:
df.isnull()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1792,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1793,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1794,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1795,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

**2."Non-Null Values in Dataset"**

In [ ]:
df.notnull()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1792,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1793,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1794,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1795,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

**3.Remove Missing Values**

In [ ]:
df.dropna()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
0,0,0,0,12,13,5,0,0,0,0,...,0,0,0,0,11,16,10,0,0,1
1,0,0,0,4,15,12,0,0,0,0,...,0,0,0,0,3,11,16,9,0,2
2,0,0,7,15,13,1,0,0,0,8,...,0,0,0,7,13,13,9,0,0,3
3,0,0,0,1,11,0,0,0,0,0,...,0,0,0,0,2,16,4,0,0,4
4,0,0,12,10,0,0,0,0,0,0,...,0,0,0,9,16,16,10,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,9
1792,0,0,6,16,13,11,1,0,0,0,...,0,0,0,6,16,14,6,0,0,0
1793,0,0,1,11,15,1,0,0,0,0,...,0,0,0,2,9,13,6,0,0,8
1794,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,9
1795,0,0,10,14,8,1,0,0,0,2,...,0,0,1,8,12,14,12,1,0,8

**4.Fill Missing Values**

In [ ]:
df.interpolate()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
0,0,0,0,12,13,5,0,0,0,0,...,0,0,0,0,11,16,10,0,0,1
1,0,0,0,4,15,12,0,0,0,0,...,0,0,0,0,3,11,16,9,0,2
2,0,0,7,15,13,1,0,0,0,8,...,0,0,0,7,13,13,9,0,0,3
3,0,0,0,1,11,0,0,0,0,0,...,0,0,0,0,2,16,4,0,0,4
4,0,0,12,10,0,0,0,0,0,0,...,0,0,0,9,16,16,10,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,9
1792,0,0,6,16,13,11,1,0,0,0,...,0,0,0,6,16,14,6,0,0,0
1793,0,0,1,11,15,1,0,0,0,0,...,0,0,0,2,9,13,6,0,0,8
1794,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,9
1795,0,0,10,14,8,1,0,0,0,2,...,0,0,1,8,12,14,12,1,0,8

**5.Checking Duplicate Records**

In [ ]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1791    False
1792    False
1793    False
1794    False
1795    False
Length: 1796, dtype: bool

**6.Removing Duplicate Records**

In [ ]:
df.drop_duplicates()

,0,0.1,5,13,9,1,0.2,0.3,0.4,0.5,...,0.23,0.24,0.25,6,13.2,10.2,0.26,0.27,0.28,0.29
0,0,0,0,12,13,5,0,0,0,0,...,0,0,0,0,11,16,10,0,0,1
1,0,0,0,4,15,12,0,0,0,0,...,0,0,0,0,3,11,16,9,0,2
2,0,0,7,15,13,1,0,0,0,8,...,0,0,0,7,13,13,9,0,0,3
3,0,0,0,1,11,0,0,0,0,0,...,0,0,0,0,2,16,4,0,0,4
4,0,0,12,10,0,0,0,0,0,0,...,0,0,0,9,16,16,10,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1791,0,0,4,10,13,6,0,0,0,1,...,0,0,0,2,14,15,9,0,0,9
1792,0,0,6,16,13,11,1,0,0,0,...,0,0,0,6,16,14,6,0,0,0
1793,0,0,1,11,15,1,0,0,0,0,...,0,0,0,2,9,13,6,0,0,8
1794,0,0,2,10,7,0,0,0,0,0,...,0,0,0,5,12,16,12,0,0,9
1795,0,0,10,14,8,1,0,0,0,2,...,0,0,1,8,12,14,12,1,0,8

# **C-Numerical functions**

**1-mean**

In [ ]:
df.mean(numeric_only=True)

0        0.000000
0.1      0.304009
5        5.204900
13      11.835189
9       11.849666
          ...
10.2    11.810134
0.26     6.767817
0.27     2.069042
0.28     0.364699
0.29     4.493318
Length: 65, dtype: float64

**2-standard deviation**

In [ ]:
df.std(numeric_only=True)

0       0.000000
0.1     0.907416
5       4.756148
13      4.249936
9       4.288055
          ...
10.2    4.935137
0.26    5.900105
0.27    4.091396
0.28    1.860620
0.29    2.864140
Length: 65, dtype: float64

**3-Median**

In [ ]:
df.median(numeric_only=True)

0        0.0
0.1      0.0
5        4.0
13      13.0
9       13.0
        ...
10.2    14.0
0.26     6.0
0.27     0.0
0.28     0.0
0.29     4.0
Length: 65, dtype: float64

**Conclusion**

In this project, we performed data preprocessing, cleaning, and basic analysis on the Digits Dataset. We inspected the dataset to understand its structure, handled missing and duplicate values, and applied numerical functions like mean, median, and standard deviation to summarize the data. After these steps, the dataset is clean, well-structured, and ready for further analysis or machine learning tasks, ensuring accuracy and reliability in any downstream applications.